name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install tox
      - name: Run tests
        run: python -m tox
